package Profile;
import Administration.Randomizer;

/**
 * Created by Felix on 02.01.2017.
 */

public class UserData {
    String username;
    String password;
    int birthday;
    int birthmonth;
    int birthyear;

    String profilePic;
    int challengesCompleted;
    int challengeAssigned;
    int reputation;
    int userID;

    public int getNewChallenge(UserData user) {
        int newID;
        int minChallengeIndex = 0;          //should be generated by the database
        int maxChallengeIndex = 5;          //should be generated by the database
        if (user.challengeAssigned == 0) {
            //generate new challenge
            int min = minChallengeIndex;
            int max = maxChallengeIndex;
            // add 1 to max because max is exclusive
            newID = 3;
            //newID = Randomizer.getRandomInt(min, max);
            //challengeRemoveFromDatabase(newID);                 //will be added to control unit
            return newID;
        } else {
            //user already has a challenge assigned, return a nope
            return -1;
        }
    }

    public int giveUp(UserData user) {
        if (user.challengeAssigned != 0) {
            //challengeAddToDatabase(user.challengeAssigned);     //will be added to control unit
            user.challengeAssigned = 0;
            return 1;
        } else {
            user.reputation -= 2;
            return 0;
        }
    }

    public String getName(UserData user) {
        return user.username;
    }

    public String getPass(UserData user) {
        return user.password;
    }

    public String getDay(UserData user) {
        return Integer.toString(user.birthday);
    }

    public String getMonth(UserData user) {
        return Integer.toString(user.birthmonth);
    }

    public String getYear(UserData user) {
        return Integer.toString(user.birthyear);
    }


}