package Profile;

/**
 * Created by Felix on 02.01.2017.
 */

public class UserData {
    private String username;
    private String password;
    private int birthday;
    private int birthmonth;
    private int birthyear;

    private String profilePic;
    private int challengesCompleted;
    private int challengeAssigned;
    private int reputation;
    private int userID;

    private int IDCount = 0;

    public UserData(String name, String pass, int day, int month, int year) {
        username = name;
        password = pass;
        birthday = day;
        birthmonth = month;
        birthyear = year;
        profilePic = "http://s3.amazonaws.com/37assets/svn/765-default-avatar.png";
        userID = generateUserID();
        challengesCompleted = 0;
        challengeAssigned = 0;
        reputation = 0;
    }

    public int getNewChallenge(UserData user) {
        int newID;
        int minChallengeIndex = 0;          //should be generated by the database
        int maxChallengeIndex = 5;          //should be generated by the database
        if (user.challengeAssigned == 0) {
            //generate new challenge
            int min = minChallengeIndex;
            int max = maxChallengeIndex;
            // add 1 to max because max is exclusive
            newID = 3;
            //newID = Randomizer.getRandomInt(min, max);
            //challengeRemoveFromDatabase(newID);                 //will be added to control unit
            return newID;
        } else {
            //user already has a challenge assigned, return a nope
            return -1;
        }
    }

    public int giveUp(UserData user) {
        if (user.challengeAssigned != 0) {
            //challengeAddToDatabase(user.challengeAssigned);     //will be added to control unit
            user.challengeAssigned = 0;
            return 1;
        } else {
            user.reputation -= 2;
            return 0;
        }
    }

    private int generateUserID() {
        int ID = IDCount;
        IDCount++;
        return ID;
    }

    public String getName() {
        return username;
    }

    public String getPass() {
        return password;
    }

    public String getDay() {
        return Integer.toString(birthday);
    }

    public String getMonth() {
        return Integer.toString(birthmonth);
    }

    public String getYear() {
        return Integer.toString(birthyear);
    }

    public int getUserID() {
        return userID;
    }

    public void setName(String name) {
        username = name;
    }

    public void setPass(String pass) {
        password = pass;
    }

    public void setDay(int day) {
        birthday = day;
    }

    public void setMonth(int month) {
        birthmonth = month;
    }

    public void setyear(int year) {
        birthyear = year;
    }
}