package Profile;

/**
 * Created by Felix on 02.01.2017.
 */

public class UserData {
    private String username;
    private String password;
    private int birthday;
    private int birthmonth;
    private int birthyear;

    private String profilePic;
    private int challengesCompleted;
    private int challengeAssigned;
    private int reputation;
    private int userID;

    public UserData(String name, String pass, int day, int month, int year) {
        username = name;
        password = pass;
        birthday = day;
        birthmonth = month;
        birthyear = year;
        profilePic = "http://s3.amazonaws.com/37assets/svn/765-default-avatar.png";
        challengesCompleted = 0;
        challengeAssigned = 0;
        reputation = 0;
    }

    public int getNewChallenge(UserData user) {
        int newID;
        int minChallengeIndex = 0;          //should be generated by the database
        int maxChallengeIndex = 5;          //should be generated by the database
        if (user.challengeAssigned == 0) {
            //generate new challenge
            int min = minChallengeIndex;
            int max = maxChallengeIndex;
            // add 1 to max because max is exclusive
            newID = 3;
            //newID = Randomizer.getRandomInt(min, max);
            //challengeRemoveFromDatabase(newID);                 //will be added to control unit
            return newID;
        } else {
            //user already has a challenge assigned, return a nope
            return -1;
        }
    }

    public int giveUp(UserData user) {
        if (user.challengeAssigned != 0) {
            //challengeAddToDatabase(user.challengeAssigned);     //will be added to control unit
            user.challengeAssigned = 0;
            return 1;
        } else {
            user.reputation -= 2;
            return 0;
        }
    }

    public String getName(UserData user) {
        return user.username;
    }

    public String getPass(UserData user) {
        return user.password;
    }

    public String getDay(UserData user) {
        return Integer.toString(user.birthday);
    }

    public String getMonth(UserData user) {
        return Integer.toString(user.birthmonth);
    }

    public String getYear(UserData user) {
        return Integer.toString(user.birthyear);
    }

    public void setName(UserData user, String name) { user.username = name; }

    public void setPass(UserData user, String pass) { user.password = pass; }

    public void setDay(UserData user, int day) { user.birthday = day; }

    public void setMonth(UserData user, int month) { user.birthmonth = month; }

    public void setyear(UserData user, int year) { user.birthyear = year; }
}